links:
  home: "home"
  help: "help"
  login: "#"
  rails:
    url: "https://www.railstutorial.org"
    book: "https://www.railstutorial.org/book"
    help: "https://www.railstutorial.org/help"
user:
  name:
    type: string
    max_length: 50
    min_length: 5
  email:
    type: string
    regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
    max_length: 255
    min_length: 5
  password:
    digits:
      digit_6: 6
  image:
    profile: 90
    list: 50
  password_reset_expired: 2
page_10: 10
digit_140: 140
digit_50: 50
digit_140: 140
digit_500_500: [500, 500]
micropost:
  image_megabytes: 5
size_img_30: 30
